/**
 * Reserved shape for the adapters capability's single contract. `forge`
 * (GitHub pull-request read/merge) was removed once its only consumers,
 * `ctxr session submit`/`land`, were replaced by the `ctxr-submit`/`ctxr-land`
 * skills driving `git`/`gh` directly (session-keeps-only-what-git-cannot-do).
 * A search kind is deferred to v2 alongside the visibility-field naming
 * decision — the registration mechanism stays kind-generic for that reason,
 * even with one kind currently registered.
 */
export type AdapterKind = 'harness-generation';

export interface Adapter<K extends AdapterKind = AdapterKind> {
  kind: K;
  id: string;
  interfaceVersion: number;
}

/**
 * adapters spec: "incompatible adapter versions are refused, not silently
 * run." One number per kind, in one place — the same discipline as every
 * other "exactly one place" constant in this codebase. Bumping one of
 * these is a deliberate, breaking change to that kind's interface.
 */
export const SUPPORTED_ADAPTER_INTERFACE_VERSION: Record<AdapterKind, number> = {
  // vendored-craft-skills spec: skillsDir joined the harness-generation interface at v2,
  // and entryFileName/render became optional (a skills-only adapter needs neither).
  'harness-generation': 2,
};

/**
 * A harness-generation adapter produces one harness-specific entry file
 * containing nothing beyond an import of AGENTS.md plus that harness's own
 * extras (harness-portability spec), when it declares one at all —
 * `entryFileName`/`render` are optional at v2 for a harness that reads the
 * canonical entry document directly. `render()`, when present, returns
 * exactly the lines placed inside contexture's managed fenced region in
 * that file — never the whole file, so a hand-authored preamble outside the
 * fence survives.
 */
/**
 * `root` is the checkout currently being reconciled — the store's absolute
 * filesystem path, typically a session worktree. Permission-rule paths that
 * describe the store's own tree (e.g. the worktree-scoping glob) are
 * anchored there, not written cwd-relative, because a session may be
 * launched with its cwd already inside a worktree rather than at the store
 * root — a cwd-relative rule would then resolve against the wrong directory.
 *
 * `mainRoot` (stabilize-write-gate-hook-path) is the store's main/canonical
 * worktree — the one persistent checkout that outlives any session worktree.
 * Use this, never `root`, for any absolute path an enforcement primitive
 * itself is invoked by (a hook command): `root` is deleted the moment the
 * session worktree that generated it lands, so a path anchored there goes
 * stale as soon as that happens.
 *
 * `binPath` is this installation's own resolved CLI entrypoint, for a
 * harness whose config needs to shell out back to `ctxr` (a generated hook
 * script). See claude-code.ts's permissionConfig for the concrete case.
 */
export interface PermissionConfigInput {
  root: string;
  mainRoot: string;
  worktreesPath: string;
  binPath: string;
}

export interface HarnessGenerationAdapter extends Adapter<'harness-generation'> {
  /**
   * vendored-craft-skills spec: the store-relative directory this harness
   * reads skills from (e.g. ".claude/skills/"). Contexture bridges this
   * directory to the store's configured (canonical) skills path rather than
   * writing skills here directly — never derived by inspecting the host
   * machine, always the adapter's declaration (or a store's override, see
   * AdapterDeclarationSchema.skills_dir).
   */
  skillsDir: string;
  /** The harness-specific file this adapter writes, relative to the store root (e.g. "CLAUDE.md"). Omit for a harness that reads AGENTS.md directly — no entry file is generated for it. */
  entryFileName?: string;
  render?(agentsMdPath: string): string[];
  /** Optional: harnesses that support a structured permission config (task 8.4). */
  permissionConfig?: {
    /** Relative to the store root (e.g. ".claude/settings.json"). */
    path: string;
    render(input: PermissionConfigInput): Record<string, unknown>;
    /**
     * Rules a previous release of this adapter emitted that the current
     * `render()` no longer does — removed by exact match before the current
     * rules are merged in, so a store whose config was generated by an
     * earlier version converges to the corrected shape. Never touches a rule
     * this adapter has never emitted, including one an operator added by hand.
     */
    retiredRules(input: PermissionConfigInput): Record<string, unknown>;
    /** Optional: an additional generated script this harness's config depends on (e.g. a PreToolUse hook). */
    hookFile?: {
      /** Filename under templates/hooks/. */
      templateFileName: string;
      /** Relative to the store root — where the rendered script is installed. */
      targetPath: string;
    };
  };
}

/**
 * Maps each adapter kind to its full, kind-specific interface — so a
 * registry lookup by kind returns something with that kind's real methods
 * (render, isAvailable, ...), not just the three common base fields.
 */
export interface AdapterForKind {
  'harness-generation': HarnessGenerationAdapter;
}

